---
services:
  traefik:
    image: docker.io/library/traefik:v3.3.2
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # - 8080:8080 # Traefik Dashboard
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CLOUDFLARE_API_EMAIL=${CLOUDFLARE_API_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    networks:
      - frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"                  # Enable Traefik for the service
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

networks:
  frontend:
    external: true  # <-- (Optional) Change this to false if you want to create a new network
